### PR TITLE
supports es 2.3 now

### PR DESCRIPTION
**Pull request by rex-chien**

### CODE REVIEW

**Comment by giantchou** [comment]
你好  请问支持ES 2.3的源码在哪里能够获取？谢谢！

**Comment by rex-chien** [comment]
@giantchou You could attempt to clone my repository. [Here](https://github.com/rex-chien/elasticsearch-analysis-jieba)

**Comment by giantchou** [comment]
@rex-chien  收到，谢谢！！！

**Comment by piaolingxue** [comment]
感谢提交 pr

**Pull request merged**
